# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# What combinations to test
environment:
  access_token:
    secure: eZOsi+qcjPGuz+iXeUmCQzIaCJZoxkeziVY23KhRrxx4t3+OjdSW9x2HT/B9d6Av

# Build version format test
version: "{build}"

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version x64

  # installing local npm packages
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - npm run image-comparison-test

artifacts:
  - path: screenshots
    name: screenshots
    type: Auto

notifications:
  # Email
  - provider: Email
    to:
      - pbicustomviz@microsoft.com
    subject: 'ImageComparisonTest. Build {{status}}'

on_failure:
  - 7z a screenshots.zip screenshots
  - appveyor PushArtifact screenshots.zip

on_success:
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "pbicvbot@microsoft.com"
 - git config --global user.name "Power BI Custom Visuals Bot"
 - git remote set-url origin https://github.com/pbicvbot/powerbi-visuals-image-comparison-tests
 - git add screenshots/*
 - git commit --allow-empty -m "Appveyor.Screenshots sync[skip ci]"
 - git push -f origin HEAD:master

cache:
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules