# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# What combinations to test
environment:
  nodejs_version: "7.7.1"
  access_token:
    secure: jkwt64TmhxwWc861PGDdv5y1oustxuPCDh8K7+0lyp/PgxQGW3vH3o4QMXAlyznG

# Build version format test
version: "{build}"

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version x64

  # installing local npm packages
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - npm run ict

notifications:
  # Email
  - provider: Email
    to:
      - pbicustomviz@microsoft.com
    subject: 'ImageComparisonTest. Build {{status}}'
  - provider: Slack
    channel: testing-img-comp
    incoming_webhook:
      secure: /ETrASibodbPcNpx0P3L9sVLbvN9FrMKJASti0kHddEu3GNXZfiXs0mZCPUqIv92cjvLCrOeoo7K0g6Z3K2kP2DIkX8nWYbiMQR1icY8Z/A=

on_finish:
  - 7z a screenshots.zip screenshots
  - appveyor PushArtifact screenshots.zip

on_success:
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "pbicvbot@microsoft.com"
 - git config --global user.name "Power BI Custom Visuals Bot"
 - git add screenshots/*
 - git commit --allow-empty -m "Appveyor.Screenshots sync[skip ci]"
 - git push -f origin HEAD:master

cache:
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules